#!/bin/bash
if [ -n "$DEBUG_BASH" ]
then
	set -x
fi

ARTIFACT_LMT="n/a"

if [ -z "$ARTIFACTORY_BASE_URL" ]
then 
	echo "\$ARTIFACTORY_BASE_URL is not set. It is needed to fetch the operator manifests from EAR. cannot proceed, exiting"
	exit 1
fi

if [ -z "$ARTIFACTORY_ARTIFACT_PATH" ]
then
        echo "\$ARTIFACTORY_ARTIFACT_PATH is not set. It is needed to fetch the operator manifests from EAR. cannot proceed, exiting"
        exit 1
fi

while :
do
	OLD_ARTIFACT_LMT="${ARTIFACT_LMT}"

	ARTIFACT_LMT=`curl -s ${CURL_FETCH_CREDS} "${ARTIFACTORY_BASE_URL}/api/storage/${ARTIFACTORY_ARTIFACT_PATH}?lastModified" | jq -r .lastModified`

	if [ "${OLD_ARTIFACT_LMT}" != "${ARTIFACT_LMT}" ] 
	then
	   kill %1 2> /dev/null
	   echo "fetching new package manifest archive, modified at ${ARTIFACT_LMT}"

	   rm -rf /tmp/manifests 2> /dev/null
	   mkdir /tmp/manifests
	   cd /tmp/manifests
	   curl -s ${CURL_FETCH_CREDS}  "${ARTIFACTORY_BASE_URL}/${ARTIFACTORY_ARTIFACT_PATH}" | tar zxv 

	   if [ $? -ne 0 ]
	   then
		echo "fetching the tar gz archive and unpacking it failed. exiting"
		exit 1
	   fi
           rm -rf /tmp/bundles.db 2> /dev/null
	   /bin/initializer -o /tmp/bundles.db

	   /bin/registry-server --database /tmp/bundles.db &
	fi
        sleep 15
done
