#!/bin/bash
set -x

if [ -z "$EAR_OPERATOR_MANIFESTS_URL" ]
then 
	echo "\$EAR_OPERATOR_MANIFESTS_URL is not set. It is needed to fetch the operator manifests from EAR. cannot proceed, exiting"
	exit 1
fi

mkdir /tmp/manifests
cd /tmp/manifests
curl ${CURL_EAR_CREDS}  "${EAR_OPERATOR_MANIFESTS_URL}" | tar zxv 

if [ $? -ne 0 ]
then
	echo "fetching the tar gz archive and unpacking it failed. exiting"
	exit 1
fi

/bin/initializer -o /tmp/bundles.db

/bin/registry-server --database /tmp/bundles.db
